### ISSUE TITLE
Game softlocks when going to the color island normally (Without teleporting/using the 0 key)

### ISSUE THREAD

**Issue by IkaRest** [tjwogud/PlanetTweaks#1]
https://user-images.githubusercontent.com/36999341/225110711-c8a47f65-9750-4548-9c53-adad17847677.mp4

**Comment by ghost** [comment]
Only happens when PlanetTweaks is installed

v2.3.1 (r101) alpha branch (Latest)
UnityModManager v0.25.5.0 (Latest)
PlanetTweaks v1.3.2 (Latest)
AdofaiTweaks v2.6.1 (Latest)
AdofaiCSL 1.1.0
DetailRP 1.0.1 (Latest)
MainBpmChanger 1.0.0 (Latest)
RainingKeys 0.4.1 (Latest)
